In [ ]:
import pandas as pd
import numpy as np

In [ ]:
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

In [ ]:
df = pd.read_csv("/content/gurgaon_final.csv")

In [ ]:
df.sample(5)

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id,latitude,longitude,locality,price_per_sqft
366,3BHK 3Baths Flat/Apartment for Sale in Godrej...,https://www.99acres.com/3-bhk-bedroom-apartmen...,Godrej Air,2.47 Crore,1829,Carpet area: 1829 (169.92 sq.m.) sqft,3,3,3 Balconies,"Study Room,Pooja Room",Sector 85 Gurgaon,27,North-East,0 to 1 Year Old,"['Genesis Hospital', 'Iris Broadway', 'Euro In...",This property faces the north-East direction. ...,"['3 Wardrobe', 'Fan', '3 Geyser', 'Light', '1 ...","['Private Garden', 'Corner Property', 'Power B...","['Connectivity: 3.7 out of 5', 'Lifestyle: 3.8...",F90493184,28.406028,76.951662,Gurgaon,"13,504"
650,3BHK 4Baths Flat/Apartment for Sale in Emaar ...,https://www.99acres.com/3-bhk-bedroom-apartmen...,Emaar MGF The Enclave,3 Crore,1920,Super Built-up area 1920(178.37 sq.m.)Carpet a...,3,4,2 Balconies,Servant Room,Sector 66 Gurgaon,5,East,1 to 5 Year Old,"['Emaar Colonnade', 'M3M Cosmopolitan', 'Elan ...",The flat is east-Facing. The floor plan additi...,"['3 Wardrobe', 'Fan', '1 Exhaust Fan', '3 Geys...","['Centrally Air Conditioned', 'Power Back-up',...","['Connectivity: 4.2 out of 5', 'Lifestyle: 4 o...",K88691678,28.400700,77.051569,Gurgaon,"15,625"
620,5BHK 5Baths Flat/Apartment for Sale in Suncit...,https://www.99acres.com/5-bhk-bedroom-apartmen...,Suncity Heights,12 Crore,5033,Super Built-up area 5033(467.58 sq.m.) sqft,5,5,3+ Balconies,"Pooja Room,Store Room,Study Room",Sector 54 Gurgaon,14,North,1 to 5 Year Old,"['Sector 54 chowk metro station', 'Sector metr...","Suncity heights in sector 54, gurgaon is a rea...","['1 Water Purifier', 'Fan', '1 Fridge', '1 Din...","['Private Garden', 'Corner Property', 'Power B...","['Construction: 3.6 out of 5', 'Amenities: 3.6...",J90563242,28.432556,77.109950,Gurgaon,"23,842"
134,3BHK 4Baths Flat/Apartment for Sale in Bestec...,https://www.99acres.com/3-bhk-bedroom-apartmen...,Bestech Park View City 2,3.1 Crore,1859,Super Built-up area 1859(172.71 sq.m.)Carpet a...,3,4,3+ Balconies,Servant Room,Sector 49 Gurgaon,8,North-East,10+ Year Old,"['Sector 55-56 Metro Station', 'Raheja Mall', ...","Park view 2, 3bhk well maintained flat, all wo...","['Fan', '6 Geyser', 'Light', '1 Modular Kitche...","['High Ceiling Height', 'False Ceiling Lightin...","['Construction: 4.1 out of 5', 'Amenities: 4 o...",C88880416,28.402967,77.045762,Gurgaon,"16,675"
161,1BHK 1Bath Flat/Apartment for Sale in Central...,https://www.99acres.com/1-bhk-bedroom-apartmen...,Central Park The Room,1.95 Crore,800,Built-up area: 800 (74.32 sq.m.) sqft,1,1,No Balcony,Study Room,Sector 48 Gurgaon,10,East,5 to 10 Year Old,"['Gurjar Samrat Jaipal Khatana Marg', 'NH 248A...",Fully serviced apartment...........,"['1 Water Purifier', 'Fan', '1 Fridge', '1 Din...","['Power Back-up', 'Vaastu Compliant']","['Connectivity: 4.3 out of 5', 'Lifestyle: 4.2...",C90070844,28.423609,77.037188,Gurgaon,"24,375"

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1564 entries, 0 to 1563
Data columns (total 24 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    1564 non-null   object
 1   link             1564 non-null   object
 2   society          1564 non-null   object
 3   price            1564 non-null   object
 4   area             1564 non-null   int64
 5   areaWithType     1564 non-null   object
 6   bedRoom          1564 non-null   int64
 7   bathroom         1564 non-null   int64
 8   balcony          1564 non-null   object
 9   additionalRoom   1564 non-null   object
 10  address          1564 non-null   object
 11  floorNum         1564 non-null   object
 12  facing           1564 non-null   object
 13  agePossession    1563 non-null   object
 14  nearbyLocations  1564 non-null   object
 15  description      1564 non-null   object
 16  furnishDetails   1564 non-null   object
 17  features         1564 non-null   object
 18  rating           1564 non-null   object
 19  property_id      1564 non-null   object
 20  latitude         1564 non-null   float64
 21  longitude        1564 non-null   float64
 22  locality         1564 non-null   object
 23  price_per_sqft   1557 non-null   object
dtypes: float64(2), int64(3), object(19)
memory usage: 293.4+ KB

In [ ]:
df.shape

(1564, 24)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.isnull().sum()

property_name      0
link               0
society            0
price              0
area               0
areaWithType       0
bedRoom            0
bathroom           0
balcony            0
additionalRoom     0
address            0
floorNum           0
facing             0
agePossession      1
nearbyLocations    0
description        0
furnishDetails     0
features           0
rating             0
property_id        0
latitude           0
longitude          0
locality           0
price_per_sqft     7
dtype: int64

In [ ]:
# Columns to drop -> property_name, link, property_id
df.drop(columns=['link','property_id'], inplace=True)

In [ ]:
df.head()

,property_name,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,latitude,longitude,locality,price_per_sqft
0,4BHK 4Baths Flat/Apartment for Sale in DLF Th...,DLF The Magnolias,45 Crore,6400,Super Built-up area 6400(594.58 sq.m.)Built-up...,4,4,3+ Balconies,"Pooja Room,Study Room,Servant Room,Others",Sector 42 Gurgaon,14,North-East,5 to 10 Year Old,"['Ambience Public School', 'Heritage Intl Xper...",Dlf magnolias: An actual gateway of iconic lif...,"['1 Water Purifier', 'Fan', '1 Fridge', '1 Exh...",['Vaastu Compliant'],[],28.454042,77.098740,Gurgaon,"83,333"
1,3BHK 3Baths Flat/Apartment for Sale in Godrej...,Godrej Meridien,2.85 Crore,1855,Super Built-up area 1855(172.34 sq.m.) sqft,3,3,3 Balconies,"Pooja Room,Study Room,Servant Room,Others",Sector 106 Gurgaon,8,East,1 to 5 Year Old,"['Dwarka Expressway', 'Euro International Scho...",Looking for a 3 bhk property for sale in gurga...,[],"['Vaastu Compliant', 'Recently Renovated', 'Pi...","['Connectivity: 3.8 out of 5', 'Lifestyle: 3.7...",28.508181,76.986806,Gurgaon,"15,363"
2,3BHK 5Baths Flat/Apartment for Sale in Experi...,Experion Windchants,6.25 Crore,3763,Super Built-up area 3763(349.59 sq.m.)Built-up...,3,5,3 Balconies,Servant Room,Sector 112 Gurgaon,6,North,5 to 10 Year Old,"['First Step Play School', 'Jai Sai Ram Hospit...",Check out this 3 bhk apartment for sale in exp...,"['Light', 'No AC', 'No Bed', 'No Chimney', 'No...",[],"['Construction: 3.7 out of 5', 'Amenities: 3.9...",28.518719,77.014458,Gurgaon,"16,609"
3,3BHK 3Baths Flat/Apartment for Sale in Godrej...,Godrej 101,3.5 Crore,2125,Super Built-up area 2125(197.42 sq.m.)Carpet a...,3,3,3 Balconies,Servant Room,Sector 79 Gurgaon,11,North,By 2027,"['Vatika Town Square-INXT', 'Naurangpur Road',...","Luxury 3 bhk apartment for sale in godrej 101,...",[],[],"['Construction: 3.4 out of 5', 'Amenities: 3.8...",28.359337,76.969227,Gurgaon,"16,470"
4,4BHK 4Baths Flat/Apartment for Sale in DLF Ne...,DLF New Town Heights 1,2.85 Crore,2727,Super Built-up area 2727(253.35 sq.m.)Built-up...,4,4,3+ Balconies,"Pooja Room,Servant Room",Sector 90 Gurgaon,4,North-West,5 to 10 Year Old,"['Manish Gallexie 91', 'RHM Public School', 'S...",This beautiful 4 bhk flat in sector 90 gurgaon...,"['5 Wardrobe', 'Fan', '1 Exhaust Fan', '5 Geys...","['Centrally Air Conditioned', 'Vaastu Complian...","['Construction: 3.6 out of 5', 'Amenities: 3.9...",28.403442,76.930775,Gurgaon,"10,451"

In [ ]:
df['society'].value_counts()

society
Godrej Air                                        50
Hero Homes                                        42
Godrej Meridien                                   39
Sobha City                                        32
DLF New Town Heights 1                            27
Emaar MGF The Palm Drive                          24
Ireo Skyon                                        22
Bestech Altura                                    22
Tulip Yellow                                      21
Smart World Gems                                  21
Ireo Uptown                                       20
M3M Heights                                       20
DLF New Town Heights 2                            20
DLF The Skycourt                                  19
Tata Primanti                                     19
Experion Windchants                               19
Ramprastha The Edge Towers                        18
Ireo The Corridors                                17
M3M The Marina                                    17
Smart World Orchard                               17
Conscient Elevate                                 16
Conscient Heritage Max                            15
Bestech Park View City 2                          15
Central Park Resorts                              14
Emaar Palm Gardens                                14
Ireo The Grand Arch                               14
Adani M2K Oyster Grande                           14
DLF The Primus                                    13
Paras Dews                                        13
DLF The Ultima                                    13
DLF Park Place                                    13
Sare Homes                                        13
Bestech Park View Spa Next                        13
Unitech Fresco                                    12
Indiabulls Enigma                                 12
M3M Woodshire                                     12
Umang Winter Hills                                12
Emaar Digihomes                                   11
Conscient Heritage One                            11
Pareena Mi Casa                                   11
DLF Regal Gardens                                 11
M3M Soulitude                                     10
La Vida by Tata Housing                           10
Krisumi Waterfall Residences                      10
ATS Triumph                                       10
Bestech Park View Grand Spa                       10
Parsvnath Exotica                                 10
Unitech Escape                                     9
Vatika Sovereign Park                              9
Shree Vardhman Victoria                            9
Greenopolis                                        9
Tulip Violet                                       9
M3M Capital                                        9
BPTP Terra                                         9
SS The Leaf                                        8
Orchid Petals                                      8
Ramprastha Primera                                 8
Ashiana Anmol                                      8
Pioneer Urban Presidia                             8
Bestech Park View Sanskruti                        7
Mapsko Mount Ville                                 7
Paras Irene                                        7
Smartworld One DXP                                 7
Ireo Victory Valley                                7
Bestech Park View Ananda                           7
Eldeco Accolade                                    7
DLF The Magnolias                                  7
M3M Skycity                                        7
ILD Greens                                         7
Mahindra Aura                                      6
Unitech Harmony                                    6
M3M Crown                                          6
ROF Ananda                                         6
ATS Tourmaline                                     6
Bestech Park View Residency                        6
Chintels Serenity                                  6
DLF New Town Heights                               6
Emaar Imperial Gardens                             6
The Close South                                    6
M3M Antalya Hills                                  6
Vatika Gurgaon 21                                  6
Alpha Corp GurgaonOne 84                           6
Godrej Nature Plus                                 6
Mahindra Luminare                                  5
Tulip Monsella                                     5
Central Park Flower Valley Aqua Front Towers       5
AIPL The Peaceful Homes                            5
Vatika City                                        5
Orris Aster Court                                  5
Vatika The Seven Lamps                             5
BPTP Spacio                                        5
Emaar Gurgaon Greens                               5
AWHO Sispal Vihar                                  5
Mapsko Royale Ville                                5
ATS Marigold                                       5
M3M Merlin                                         5
ATS Kocoon                                         5
Spaze Privy AT4                                    5
Signature Global City 92                           5
DLF The Crest                                      5
Sare Crescent Parc                                 5
Puri Emerald Bay                                   5
Vatika Seven Elements                              5
Vipul Lavanya                                      5
Sare Petioles                                      5
Elan The Presidential                              5
Mapsko Paradise                                    4
DLF The Aralias                                    4
M3M Escala                                         4
DLF The Camellias                                  4
DLF The Belaire                                    4
BPTP Mansions Park Prime                           4
DLF The Icon                                       4
Unitech Uniworld Gardens 2                         4
Birla Navya                                        4
Godrej Habitat                                     4
GLS Arawali Homes                                  4
M3M Golfestate                                     4
Satya The Hermitage                                4
Orris Carnation Residency                          4
Trump Tower                                        4
GPL Eden Heights                                   4
Altura at DXP 92                                   4
DLF Gardencity Enclave                             4
Godrej Zenith                                      4
M3M Mansion                                        4
Antriksh Heights                                   4
Spaze Privvy The Address                           4
County The Center Court                            4
Emaar MGF Emerald Floors Premier                   4
Orris Aster Court Premier                          3
Microtek Greenburg                                 3
Tulip Purple                                       3
Emaar Mgf Palm Terraces Select                     3
Bestech Park View City                             3
Signature Global De Luxe DXP                       3
Pioneer Park                                       3
Vatika City Homes                                  3
Tata Gurgaon Gateway                               3
Brisk Lumbini Terrace Homes                        3
M3M Golf Hills                                     3
The Close North                                    3
Experion The Heartsong                             3
Unitech Uniworld City                              3
Tashee Capital Gateway                             3
BPTP Freedom Park Life                             3
AWHO Shanti Vihar                                  3
Lotus Elise                                        3
Signature Global Park                              3
Tulip Orange                                       3
Indiabulls Centrum Park                            3
Vipul Belmonte                                     3
DLF The Pinnacle                                   3
Godrej Icon                                        3
Mapsko Casa Bella                                  3
Shapoorji Pallonji Joyville Gurugram               3
BPTP Park Serene                                   2
Signature The Roselia                              2
DLF Windsor Court                                  2
Cosmos Express 99                                  2
Parsvnath Green Ville                              2
Signature Global Titanium SPR                      2
Central Park Resort Belgravia Residences           2
M3M Natura                                         2
SS Linden Floors                                   2
Signature Global City 81                           2
Dhoot Time Residency                               2
Pivotal Paradise                                   2
Central Park The Room                              2
Signature Global Park 4                            2
Unitech The Residences                             2
DLF Express Greens                                 2
Imperia The Esfera                                 2
Anant Raj                                          2
Pioneer Araya                                      2
Central Park Flower Valley                         2
M3M Ikonic                                         2
DLF Garden City Floors                             2
M3M Sierra 68                                      2
TARC Ishva                                         2
Unitech The World Spa West                         2
Emaar MGF The Enclave                              2
Conscient Parq                                     2
Signature Global Orchard Avenue 2                  2
Godrej Vrikshya                                    2
Puri Diplomatic Residences                         2
Ansal Harmony Homes                                2
M3M Latitude                                       2
Suncity Avenue 102                                 2
Emperium Premio                                    2
Assotech Blith                                     2
Pareena Express Heights                            2
Kashish Manor One                                  2
Suncity Platinum Towers                            2
Ashiana Mulberry                                   2
TARC Maceo                                         2
Raheja Navodaya                                    2
City Cooperative Society                           2
Godrej 101                                         1
BPTP Park Generations                              1
Emaar MGF Palm Hills                               1
Elan The Emperor                                   1
Tulip Crimson                                      1
Viridian The Plaza 106                             1
DLF The Grove                                      1
SAS Arcadia                                        1
BPTP Amstoria                                      1
Park Royal Apartment                               1
DLF Ridgewood Estate                               1
DLF Beverly Park                                   1
Max Estate 360                                     1
Breez Global Hill View                             1
Signature Global Infinity                          1
City Group Housing Society                         1
Godrej Astra                                       1
Pyramid Urban Homes 2                              1
Laburnum Victory Floors                            1
SBTL Caladium                                      1
BPTP Amstoria Verti Greens                         1
Signature Global The Millennia 2                   1
Divya Apartment                                    1
Central Park Flower Valley Flamingo Floors         1
CGHS Prithvi Apartments                            1
Millenium Residency                                1
Krrish Provence Estate                             1
Adani Oyster Greens                                1
CHD Avenue 71                                      1
AIPL Zen Residences                                1
Adani Lushlands                                    1
Omaxe The Nile                                     1
Lord Krishna CGHS                                  1
Oriental Valley CHS                                1
Smartworld The Edition                             1
Maruti Kunj , Bhondsi                              1
4S The Aurrum                                      1
Sector 62 ,Emaar New Project                       1
Salcon The Verandas                                1
Signature Global Grand IVA                         1
Kendriya Vihar                                     1
MRG Crown                                          1
Vatika Lifestyle Homes                             1
Suncity Vatsal Valley                              1
Pyramid Square 67A                                 1
Adore The Select Premia                            1
Vatika Boulevard Residences and Heights            1
Central Park Resorts Beau Villas                   1
Pyramid Heights                                    1
Suncity Heights                                    1
Park View Apartment                                1
Puri Diplomatic Greens                             1
ILD Grand                                          1
DLF The Summit                                     1
Smart World Sky arc                                1
Emaar Palm Premier                                 1
DLF Belvedere Towers                               1
Emaar MGF Emerald Estate                           1
MSL Apartments                                     1
Trump Tower 2                                      1
Vipul Greens                                       1
Adani Samsara Avasa                                1
Unitech Uniworld Gardens                           1
Samanvay Apartment                                 1
Breez Global Heights                               1
Ansal API Sushant Estate                           1
Central Park                                       1
Emaar Emerald Hills                                1
Hamlin Apartments                                  1
Breez Flora Avenue,                                1
Sobha International City Phase 3                   1
Signature Global City                              1
Ireo Victory Valley,Golf course extension road     1
ROF Aalayas                                        1
Godrej Frontier                                    1
Ambience Caitriona                                 1
The Retreat                                        1
Piedmont Taksila heights                           1
Block C                                            1
DLF Privana West                                   1
Eldeco Acclaim                                     1
Smartworld Sky Arc                                 1
Godrej Nature Plus Serenity                        1
Apex Our Homes                                     1
Raheja Vedaanta                                    1
Delphine Central Park Estates                      1
Diamond court                                      1
Royal Palm Apartments                              1
SS One                                             1
DLF Trinity Towers                                 1
M3M Polo Suites                                    1
SS Southend Floors                                 1
Ramprastha The Atrium                              1
DLF ROYAL RESIDENCES                               1
Smriti Apartment                                   1
DLF Hamilton Court                                 1
Balidan Heights                                    1
Raheja Atharva                                     1
Eldeco Fairway Reserve                             1
La Lagune                                          1
Mangal Murti Apartments                            1
Capital Residences 360                             1
CGHS Doordarshan Apartments                        1
Malibu Towers                                      1
DLF Regency Park 1                                 1
Tulip White                                        1
DLF Princeton Estate                               1
Jammu and Kashmir Bank Employees CGHS              1
Smartworld Sky ARC                                 1
Paras The Manor                                    1
Khushboo Apartment                                 1
Signature Global City 63A                          1
Technocrat Society                                 1
Suncity Avenue 76                                  1
Tulip Ivory                                        1
BPTP Park Prime                                    1
Name: count, dtype: int64

In [ ]:
df['society'].value_counts().shape

(314,)

In [ ]:
df['society'] = df['society'].str.lower()

In [ ]:
df['society'].value_counts().shape

(313,)

In [ ]:
df['price'].value_counts()

price
2.5 Crore           32
2.6 Crore           27
2.8 Crore           22
2.55 Crore          22
2.1 Crore           22
2.4 Crore           21
3.3 Crore           21
2.15 Crore          21
2.3 Crore           21
1.75 Crore          21
2.35 Crore          20
2.05 Crore          20
2.2 Crore           19
2.65 Crore          18
2.85 Crore          18
2 Crore             18
3.6 Crore           17
2.45 Crore          17
3.2 Crore           17
2.25 Crore          17
3 Crore             16
1.9 Crore           16
1.35 Crore          15
2.9 Crore           15
1.7 Crore           15
1.95 Crore          13
4 Crore             13
1.85 Crore          13
3.1 Crore           12
3.45 Crore          12
3.9 Crore           12
3.35 Crore          11
4.15 Crore          11
3.5 Crore           11
4.5 Crore           10
4.95 Crore          10
2.75 Crore          10
4.1 Crore           10
3.15 Crore          10
3.4 Crore           10
1.8 Crore           10
1.55 Crore           9
2.95 Crore           9
3.7 Crore            9
1.65 Crore           9
3.25 Crore           9
2.7 Crore            9
3.95 Crore           9
4.7 Crore            8
5.15 Crore           8
1.45 Crore           8
4.2 Crore            8
4.25 Crore           8
1.4 Crore            8
1.5 Crore            8
5.25 Crore           7
3.05 Crore           7
1.3 Crore            7
2.12 Crore           7
2.32 Crore           7
4.3 Crore            7
3.75 Crore           6
4.6 Crore            6
2.48 Crore           6
1.78 Crore           6
7.45 Crore           6
3.85 Crore           6
2.27 Crore           6
4.85 Crore           6
1.6 Crore            6
1.36 Crore           6
2.22 Crore           6
4.8 Crore            6
1.72 Crore           5
1.57 Crore           5
1.48 Crore           5
1.66 Crore           5
7 Crore              5
3.65 Crore           5
1.68 Crore           5
2.38 Crore           5
3.55 Crore           5
4.05 Crore           5
1.69 Crore           5
5 Crore              5
2.42 Crore           5
1.62 Crore           5
5.35 Crore           5
6.5 Crore            5
3.8 Crore            5
5.1 Crore            5
4.75 Crore           4
12 Crore             4
6.25 Crore           4
5.7 Crore            4
1.84 Crore           4
4.45 Crore           4
8 Crore              4
1.52 Crore           4
2.49 Crore           4
5.2 Crore            4
1.88 Crore           4
3.22 Crore           4
5.3 Crore            4
7.5 Crore            4
6 Crore              4
4.9 Crore            4
2.03 Crore           4
5.5 Crore            4
1.64 Crore           4
3.68 Crore           4
1.25 Crore           4
5.05 Crore           4
8.5 Crore            4
3.58 Crore           4
1.73 Crore           4
3.51 Crore           4
1.43 Crore           3
6.7 Crore            3
6.15 Crore           3
10.5 Crore           3
62 Lac               3
3.99 Crore           3
1.28 Crore           3
2.34 Crore           3
5.65 Crore           3
2.52 Crore           3
1.05 Crore           3
2.14 Crore           3
2.98 Crore           3
1.15 Crore           3
2.51 Crore           3
1.32 Crore           3
1.58 Crore           3
2.71 Crore           3
1.2 Crore            3
4.65 Crore           3
45 Crore             3
1.22 Crore           3
1.41 Crore           3
1.38 Crore           3
5.85 Crore           3
1.98 Crore           3
5.6 Crore            3
5.75 Crore           3
2.18 Crore           3
2.08 Crore           3
2.76 Crore           2
2.19 Crore           2
6.95 Crore           2
3.64 Crore           2
3.32 Crore           2
2.68 Crore           2
2.72 Crore           2
85 Lac               2
1.67 Crore           2
6.3 Crore            2
13.5 Crore           2
1.08 Crore           2
4.35 Crore           2
3.36 Crore           2
3.19 Crore           2
2.21 Crore           2
1.92 Crore           2
3.11 Crore           2
1.06 Crore           2
1.42 Crore           2
82 Lac               2
1.39 Crore           2
5.12 Crore           2
10.95 Crore          2
7.25 Crore           2
9.7 Crore            2
1 Crore              2
1.44 Crore           2
3.72 Crore           2
2.79 Crore           2
5.99 Crore           2
1.49 Crore           2
21 Crore             2
2.64 Crore           2
43 Lac               2
4.4 Crore            2
32 Crore             2
3.49 Crore           2
2.41 Crore           2
3.48 Crore           2
2.29 Crore           2
2.11 Crore           2
9.5 Crore            2
2.77 Crore           2
3.77 Crore           2
1.83 Crore           2
1.97 Crore           2
1.34 Crore           2
10.25 Crore          2
3.67 Crore           2
2.44 Crore           2
15.5 Crore           2
7.1 Crore            2
6.2 Crore            2
3.78 Crore           2
2.58 Crore           2
17 Crore             2
2.78 Crore           2
1.87 Crore           2
3.92 Crore           2
1.56 Crore           2
8.25 Crore           2
2.47 Crore           2
65 Lac               2
3.87 Crore           2
5.95 Crore           2
58 Lac               2
11 Crore             2
2.56 Crore           2
37 Crore             2
3.29 Crore           2
1.51 Crore           2
1.1 Crore            2
7.3 Crore            2
2.53 Crore           2
1.59 Crore           2
4.01 Crore           2
5.8 Crore            2
5.9 Crore            2
2.82 Crore           2
2.07 Crore           2
1.18 Crore           2
1.63 Crore           2
3.41 Crore           2
10.05 Crore          1
7.9 Crore            1
14.35 Crore          1
3.98 Crore           1
10.39 Crore          1
4.29 Crore           1
2.84 Crore           1
7.38 Crore           1
4.52 Crore           1
7.69 Crore           1
9.51 Crore           1
10.45 Crore          1
1.86 Crore           1
6.65 Crore           1
3.04 Crore           1
2.81 Crore           1
10.9 Crore           1
3.24 Crore           1
22 Crore             1
8.53 Crore           1
13 Crore             1
3.46 Crore           1
1.61 Crore           1
12.25 Crore          1
1.29 Crore           1
3.91 Crore           1
6.22 Crore           1
5.49 Crore           1
11.5 Crore           1
42 Crore             1
1.17 Crore           1
13.75 Crore          1
48 Crore             1
4.99 Crore           1
2.57 Crore           1
28.34 Crore          1
73 Lac               1
2.96 Crore           1
8.7 Crore            1
2.02 Crore           1
7.04 Crore           1
68 Lac               1
67.99 Lac            1
2.33 Crore           1
9.9 Crore            1
16 Crore             1
2.86 Crore           1
10 Crore             1
75 Lac               1
6.45 Crore           1
13.05 Crore          1
10.8 Crore           1
3.52 Crore           1
65 Crore             1
3.38 Crore           1
3.56 Crore           1
6.55 Crore           1
3.39 Crore           1
13.1 Crore           1
7.26 Crore           1
14.8 Crore           1
3.13 Crore           1
3.81 Crore           1
1.76 Crore           1
2.31 Crore           1
2.43 Crore           1
4.86 Crore           1
1.79 Crore           1
7.4 Crore            1
4.46 Crore           1
3.08 Crore           1
58.5 Lac             1
60 Lac               1
10.15 Crore          1
1.99 Crore           1
1.96 Crore           1
3.47 Crore           1
23 Crore             1
4.42 Crore           1
4.28 Crore           1
77 Lac               1
1.01 Crore           1
5.27 Crore           1
9.85 Crore           1
1.03 Crore           1
3.84 Crore           1
20.8 Crore           1
70 Lac               1
6.75 Crore           1
4.09 Crore           1
1.82 Crore           1
11.97 Crore          1
1.26 Crore           1
7.05 Crore           1
2.88 Crore           1
7.49 Crore           1
3.21 Crore           1
2.91 Crore           1
71 Crore             1
4.14 Crore           1
7.75 Crore           1
3.12 Crore           1
2.61 Crore           1
95 Lac               1
15.75 Crore          1
17.5 Crore           1
2.69 Crore           1
3.42 Crore           1
6.6 Crore            1
75 Crore             1
83 Lac               1
73 Crore             1
2.01 Crore           1
5.69 Crore           1
5.52 Crore           1
47 Lac               1
4.18 Crore           1
5.32 Crore           1
11.65 Crore          1
8.15 Crore           1
2.94 Crore           1
2.36 Crore           1
2.62 Crore           1
5.4 Crore            1
59.95 Lac            1
2.39 Crore           1
47.1 Crore           1
57 Lac               1
4.34 Crore           1
12.75 Crore          1
46 Lac               1
1.53 Crore           1
3.28 Crore           1
6.1 Crore            1
3.66 Crore           1
4.76 Crore           1
61.9 Lac             1
2.89 Crore           1
6.43 Crore           1
4.49 Crore           1
12.9 Crore           1
3.74 Crore           1
1.71 Crore           1
8.9 Crore            1
6.8 Crore            1
85 Crore             1
2.99 Crore           1
2.16 Crore           1
4.73 Crore           1
2.24 Crore           1
5.55 Crore           1
9.95 Crore           1
6.18 Crore           1
3.33 Crore           1
Price on Request     1
2.04 Crore           1
3.14 Crore           1
6.71 Crore           1
12.4 Crore           1
3.18 Crore           1
4.22 Crore           1
67 Lac               1
2.66 Crore           1
33.67 Crore          1
39 Crore             1
1.21 Crore           1
5.18 Crore           1
4.11 Crore           1
7.95 Crore           1
2.28 Crore           1
2.54 Crore           1
7.8 Crore            1
3.07 Crore           1
24 Crore             1
3.93 Crore           1
55 Lac               1
4.68 Crore           1
71 Lac               1
1.31 Crore           1
4.16 Crore           1
12.6 Crore           1
5.31 Crore           1
3.69 Crore           1
2.73 Crore           1
4.36 Crore           1
4.84 Crore           1
3.02 Crore           1
59 Lac               1
6.31 Crore           1
15 Crore             1
12.5 Crore           1
4.38 Crore           1
1.46 Crore           1
2.83 Crore           1
8.95 Crore           1
3.82 Crore           1
1.74 Crore           1
8.3 Crore            1
6.85 Crore           1
6.26 Crore           1
14.5 Crore           1
3.89 Crore           1
8.8 Crore            1
18.5 Crore           1
7.21 Crore           1
4.17 Crore           1
8.4 Crore            1
6.08 Crore           1
1.02 Crore           1
1.27 Crore           1
9 Crore              1
6.34 Crore           1
16.7 Crore           1
Name: count, dtype: int64

In [ ]:
df[df['price'] == 'Price on Request']

,property_name,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,latitude,longitude,locality,price_per_sqft
1092,3BHK 3Baths Flat/Apartment for Sale in Consci...,conscient parq,Price on Request,2375,Carpet area: 2375 (220.64 sq.m.) sqft,3,3,3 Balconies,Servant Room,Sector 80 Gurgaon,19,North,Nov 2029,"['Pooja Clinic', 'Dr. Sahil Clinic', 'Prakash ...",The floor plan additionally contains 3 bedroom...,[],"['Lift(s)', 'Swimming Pool', 'Park', 'Fitness ...",[],28.365864,76.955664,Gurgaon,NaN

In [ ]:
df = df[df['price'] != 'Price on Request']

In [ ]:
df.head()

,property_name,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,latitude,longitude,locality,price_per_sqft
0,4BHK 4Baths Flat/Apartment for Sale in DLF Th...,dlf the magnolias,45 Crore,6400,Super Built-up area 6400(594.58 sq.m.)Built-up...,4,4,3+ Balconies,"Pooja Room,Study Room,Servant Room,Others",Sector 42 Gurgaon,14,North-East,5 to 10 Year Old,"['Ambience Public School', 'Heritage Intl Xper...",Dlf magnolias: An actual gateway of iconic lif...,"['1 Water Purifier', 'Fan', '1 Fridge', '1 Exh...",['Vaastu Compliant'],[],28.454042,77.098740,Gurgaon,"83,333"
1,3BHK 3Baths Flat/Apartment for Sale in Godrej...,godrej meridien,2.85 Crore,1855,Super Built-up area 1855(172.34 sq.m.) sqft,3,3,3 Balconies,"Pooja Room,Study Room,Servant Room,Others",Sector 106 Gurgaon,8,East,1 to 5 Year Old,"['Dwarka Expressway', 'Euro International Scho...",Looking for a 3 bhk property for sale in gurga...,[],"['Vaastu Compliant', 'Recently Renovated', 'Pi...","['Connectivity: 3.8 out of 5', 'Lifestyle: 3.7...",28.508181,76.986806,Gurgaon,"15,363"
2,3BHK 5Baths Flat/Apartment for Sale in Experi...,experion windchants,6.25 Crore,3763,Super Built-up area 3763(349.59 sq.m.)Built-up...,3,5,3 Balconies,Servant Room,Sector 112 Gurgaon,6,North,5 to 10 Year Old,"['First Step Play School', 'Jai Sai Ram Hospit...",Check out this 3 bhk apartment for sale in exp...,"['Light', 'No AC', 'No Bed', 'No Chimney', 'No...",[],"['Construction: 3.7 out of 5', 'Amenities: 3.9...",28.518719,77.014458,Gurgaon,"16,609"
3,3BHK 3Baths Flat/Apartment for Sale in Godrej...,godrej 101,3.5 Crore,2125,Super Built-up area 2125(197.42 sq.m.)Carpet a...,3,3,3 Balconies,Servant Room,Sector 79 Gurgaon,11,North,By 2027,"['Vatika Town Square-INXT', 'Naurangpur Road',...","Luxury 3 bhk apartment for sale in godrej 101,...",[],[],"['Construction: 3.4 out of 5', 'Amenities: 3.8...",28.359337,76.969227,Gurgaon,"16,470"
4,4BHK 4Baths Flat/Apartment for Sale in DLF Ne...,dlf new town heights 1,2.85 Crore,2727,Super Built-up area 2727(253.35 sq.m.)Built-up...,4,4,3+ Balconies,"Pooja Room,Servant Room",Sector 90 Gurgaon,4,North-West,5 to 10 Year Old,"['Manish Gallexie 91', 'RHM Public School', 'S...",This beautiful 4 bhk flat in sector 90 gurgaon...,"['5 Wardrobe', 'Fan', '1 Exhaust Fan', '5 Geys...","['Centrally Air Conditioned', 'Vaastu Complian...","['Construction: 3.6 out of 5', 'Amenities: 3.9...",28.403442,76.930775,Gurgaon,"10,451"

In [ ]:
def treat_price(x):
    if type(x) == float:
        return x
    else:
        if x[1] == 'Lac':
            return round(float(x[0])/100,2)
        else:
            return round(float(x[0]),2)

In [ ]:
df['price'] = df['price'].str.split(' ').apply(treat_price)

In [ ]:
df.head()

,property_name,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,latitude,longitude,locality,price_per_sqft
0,4BHK 4Baths Flat/Apartment for Sale in DLF Th...,dlf the magnolias,45.00,6400,Super Built-up area 6400(594.58 sq.m.)Built-up...,4,4,3+ Balconies,"Pooja Room,Study Room,Servant Room,Others",Sector 42 Gurgaon,14,North-East,5 to 10 Year Old,"['Ambience Public School', 'Heritage Intl Xper...",Dlf magnolias: An actual gateway of iconic lif...,"['1 Water Purifier', 'Fan', '1 Fridge', '1 Exh...",['Vaastu Compliant'],[],28.454042,77.098740,Gurgaon,"83,333"
1,3BHK 3Baths Flat/Apartment for Sale in Godrej...,godrej meridien,2.85,1855,Super Built-up area 1855(172.34 sq.m.) sqft,3,3,3 Balconies,"Pooja Room,Study Room,Servant Room,Others",Sector 106 Gurgaon,8,East,1 to 5 Year Old,"['Dwarka Expressway', 'Euro International Scho...",Looking for a 3 bhk property for sale in gurga...,[],"['Vaastu Compliant', 'Recently Renovated', 'Pi...","['Connectivity: 3.8 out of 5', 'Lifestyle: 3.7...",28.508181,76.986806,Gurgaon,"15,363"
2,3BHK 5Baths Flat/Apartment for Sale in Experi...,experion windchants,6.25,3763,Super Built-up area 3763(349.59 sq.m.)Built-up...,3,5,3 Balconies,Servant Room,Sector 112 Gurgaon,6,North,5 to 10 Year Old,"['First Step Play School', 'Jai Sai Ram Hospit...",Check out this 3 bhk apartment for sale in exp...,"['Light', 'No AC', 'No Bed', 'No Chimney', 'No...",[],"['Construction: 3.7 out of 5', 'Amenities: 3.9...",28.518719,77.014458,Gurgaon,"16,609"
3,3BHK 3Baths Flat/Apartment for Sale in Godrej...,godrej 101,3.50,2125,Super Built-up area 2125(197.42 sq.m.)Carpet a...,3,3,3 Balconies,Servant Room,Sector 79 Gurgaon,11,North,By 2027,"['Vatika Town Square-INXT', 'Naurangpur Road',...","Luxury 3 bhk apartment for sale in godrej 101,...",[],[],"['Construction: 3.4 out of 5', 'Amenities: 3.8...",28.359337,76.969227,Gurgaon,"16,470"
4,4BHK 4Baths Flat/Apartment for Sale in DLF Ne...,dlf new town heights 1,2.85,2727,Super Built-up area 2727(253.35 sq.m.)Built-up...,4,4,3+ Balconies,"Pooja Room,Servant Room",Sector 90 Gurgaon,4,North-West,5 to 10 Year Old,"['Manish Gallexie 91', 'RHM Public School', 'S...",This beautiful 4 bhk flat in sector 90 gurgaon...,"['5 Wardrobe', 'Fan', '1 Exhaust Fan', '5 Geys...","['Centrally Air Conditioned', 'Vaastu Complian...","['Construction: 3.6 out of 5', 'Amenities: 3.9...",28.403442,76.930775,Gurgaon,"10,451"

In [ ]:
df['price_per_sqft'] = round((df['price'] * 10000000) / df['area'])

In [ ]:
df.head()

,property_name,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,latitude,longitude,locality,price_per_sqft
0,4BHK 4Baths Flat/Apartment for Sale in DLF Th...,dlf the magnolias,45.00,6400,Super Built-up area 6400(594.58 sq.m.)Built-up...,4,4,3+ Balconies,"Pooja Room,Study Room,Servant Room,Others",Sector 42 Gurgaon,14,North-East,5 to 10 Year Old,"['Ambience Public School', 'Heritage Intl Xper...",Dlf magnolias: An actual gateway of iconic lif...,"['1 Water Purifier', 'Fan', '1 Fridge', '1 Exh...",['Vaastu Compliant'],[],28.454042,77.098740,Gurgaon,70312.0
1,3BHK 3Baths Flat/Apartment for Sale in Godrej...,godrej meridien,2.85,1855,Super Built-up area 1855(172.34 sq.m.) sqft,3,3,3 Balconies,"Pooja Room,Study Room,Servant Room,Others",Sector 106 Gurgaon,8,East,1 to 5 Year Old,"['Dwarka Expressway', 'Euro International Scho...",Looking for a 3 bhk property for sale in gurga...,[],"['Vaastu Compliant', 'Recently Renovated', 'Pi...","['Connectivity: 3.8 out of 5', 'Lifestyle: 3.7...",28.508181,76.986806,Gurgaon,15364.0
2,3BHK 5Baths Flat/Apartment for Sale in Experi...,experion windchants,6.25,3763,Super Built-up area 3763(349.59 sq.m.)Built-up...,3,5,3 Balconies,Servant Room,Sector 112 Gurgaon,6,North,5 to 10 Year Old,"['First Step Play School', 'Jai Sai Ram Hospit...",Check out this 3 bhk apartment for sale in exp...,"['Light', 'No AC', 'No Bed', 'No Chimney', 'No...",[],"['Construction: 3.7 out of 5', 'Amenities: 3.9...",28.518719,77.014458,Gurgaon,16609.0
3,3BHK 3Baths Flat/Apartment for Sale in Godrej...,godrej 101,3.50,2125,Super Built-up area 2125(197.42 sq.m.)Carpet a...,3,3,3 Balconies,Servant Room,Sector 79 Gurgaon,11,North,By 2027,"['Vatika Town Square-INXT', 'Naurangpur Road',...","Luxury 3 bhk apartment for sale in godrej 101,...",[],[],"['Construction: 3.4 out of 5', 'Amenities: 3.8...",28.359337,76.969227,Gurgaon,16471.0
4,4BHK 4Baths Flat/Apartment for Sale in DLF Ne...,dlf new town heights 1,2.85,2727,Super Built-up area 2727(253.35 sq.m.)Built-up...,4,4,3+ Balconies,"Pooja Room,Servant Room",Sector 90 Gurgaon,4,North-West,5 to 10 Year Old,"['Manish Gallexie 91', 'RHM Public School', 'S...",This beautiful 4 bhk flat in sector 90 gurgaon...,"['5 Wardrobe', 'Fan', '1 Exhaust Fan', '5 Geys...","['Centrally Air Conditioned', 'Vaastu Complian...","['Construction: 3.6 out of 5', 'Amenities: 3.9...",28.403442,76.930775,Gurgaon,10451.0

In [ ]:
df['bedRoom'].value_counts()

bedRoom
3    890
4    388
2    253
5     25
1      6
7      1
Name: count, dtype: int64

In [ ]:
df['bathroom'].value_counts()

bathroom
3    606
4    454
2    296
5    156
6     34
1      9
7      4
8      4
Name: count, dtype: int64

In [ ]:
df['balcony'].value_counts()

balcony
3+ Balconies    600
3 Balconies     571
2 Balconies     344
1 Balcony        44
No Balcony        4
Name: count, dtype: int64

In [ ]:
df['balcony'] = df['balcony'].str.split(' ').str.get(0).str.replace('No','0')

In [ ]:
df['balcony'].value_counts()

balcony
3+    600
3     571
2     344
1      44
0       4
Name: count, dtype: int64

In [ ]:
df.head()

,property_name,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,latitude,longitude,locality,price_per_sqft
0,4BHK 4Baths Flat/Apartment for Sale in DLF Th...,dlf the magnolias,45.00,6400,Super Built-up area 6400(594.58 sq.m.)Built-up...,4,4,3+,"Pooja Room,Study Room,Servant Room,Others",Sector 42 Gurgaon,14,North-East,5 to 10 Year Old,"['Ambience Public School', 'Heritage Intl Xper...",Dlf magnolias: An actual gateway of iconic lif...,"['1 Water Purifier', 'Fan', '1 Fridge', '1 Exh...",['Vaastu Compliant'],[],28.454042,77.098740,Gurgaon,70312.0
1,3BHK 3Baths Flat/Apartment for Sale in Godrej...,godrej meridien,2.85,1855,Super Built-up area 1855(172.34 sq.m.) sqft,3,3,3,"Pooja Room,Study Room,Servant Room,Others",Sector 106 Gurgaon,8,East,1 to 5 Year Old,"['Dwarka Expressway', 'Euro International Scho...",Looking for a 3 bhk property for sale in gurga...,[],"['Vaastu Compliant', 'Recently Renovated', 'Pi...","['Connectivity: 3.8 out of 5', 'Lifestyle: 3.7...",28.508181,76.986806,Gurgaon,15364.0
2,3BHK 5Baths Flat/Apartment for Sale in Experi...,experion windchants,6.25,3763,Super Built-up area 3763(349.59 sq.m.)Built-up...,3,5,3,Servant Room,Sector 112 Gurgaon,6,North,5 to 10 Year Old,"['First Step Play School', 'Jai Sai Ram Hospit...",Check out this 3 bhk apartment for sale in exp...,"['Light', 'No AC', 'No Bed', 'No Chimney', 'No...",[],"['Construction: 3.7 out of 5', 'Amenities: 3.9...",28.518719,77.014458,Gurgaon,16609.0
3,3BHK 3Baths Flat/Apartment for Sale in Godrej...,godrej 101,3.50,2125,Super Built-up area 2125(197.42 sq.m.)Carpet a...,3,3,3,Servant Room,Sector 79 Gurgaon,11,North,By 2027,"['Vatika Town Square-INXT', 'Naurangpur Road',...","Luxury 3 bhk apartment for sale in godrej 101,...",[],[],"['Construction: 3.4 out of 5', 'Amenities: 3.8...",28.359337,76.969227,Gurgaon,16471.0
4,4BHK 4Baths Flat/Apartment for Sale in DLF Ne...,dlf new town heights 1,2.85,2727,Super Built-up area 2727(253.35 sq.m.)Built-up...,4,4,3+,"Pooja Room,Servant Room",Sector 90 Gurgaon,4,North-West,5 to 10 Year Old,"['Manish Gallexie 91', 'RHM Public School', 'S...",This beautiful 4 bhk flat in sector 90 gurgaon...,"['5 Wardrobe', 'Fan', '1 Exhaust Fan', '5 Geys...","['Centrally Air Conditioned', 'Vaastu Complian...","['Construction: 3.6 out of 5', 'Amenities: 3.9...",28.403442,76.930775,Gurgaon,10451.0

In [ ]:
df['additionalRoom'].value_counts()

additionalRoom
Servant Room                                            641
Study Room                                              155
Pooja Room                                              115
Others                                                  107
Pooja Room,Servant Room                                  83
Study Room,Servant Room                                  66
Store Room                                               62
Pooja Room,Study Room,Servant Room,Store Room            43
Servant Room,Pooja Room                                  34
Servant Room,Store Room                                  26
Pooja Room,Study Room,Servant Room                       25
Servant Room,Others                                      18
Study Room,Pooja Room                                    15
Servant Room,Study Room                                  15
Study Room,Store Room                                    14
Study Room,Others                                        13
Pooja Room,Servant Room,Study Room                        9
Servant Room,Pooja Room,Study Room,Store Room             9
Pooja Room,Study Room,Servant Room,Others                 8
Pooja Room,Study Room                                     7
Study Room,Servant Room,Pooja Room,Store Room             5
Study Room,Servant Room,Pooja Room                        5
Others,Servant Room                                       5
Pooja Room,Study Room,Others,Servant Room                 4
Servant Room,Others,Pooja Room                            4
Servant Room,Study Room,Store Room                        3
Servant Room,Study Room,Pooja Room,Store Room             3
Store Room,Servant Room                                   3
Servant Room,Study Room,Pooja Room                        3
Pooja Room,Study Room,Servant Room,Others,Store Room      3
Pooja Room,Study Room,Store Room                          3
Pooja Room,Store Room                                     3
Servant Room,Pooja Room,Study Room,Others                 3
Study Room,Others,Servant Room                            3
Store Room,Pooja Room                                     3
Pooja Room,Servant Room,Store Room                        3
Pooja Room,Servant Room,Study Room,Others                 2
Others,Study Room                                         2
Study Room,Servant Room,Store Room                        2
Servant Room,Pooja Room,Study Room                        2
Pooja Room,Others                                         2
Study Room,Pooja Room,Servant Room                        2
Study Room,Store Room,Servant Room                        2
Others,Servant Room,Study Room,Pooja Room                 2
Servant Room,Study Room,Others                            2
Study Room,Pooja Room,Servant Room,Store Room             2
Study Room,Store Room,Others                              2
Pooja Room,Servant Room,Others                            2
Study Room,Pooja Room,Others                              1
Servant Room,Store Room,Study Room,Pooja Room             1
Store Room,Study Room,Pooja Room                          1
Pooja Room,Store Room,Study Room                          1
Store Room,Servant Room,Pooja Room                        1
Servant Room,Study Room,Pooja Room,Others                 1
Pooja Room,Store Room,Servant Room                        1
Pooja Room,Study Room,Store Room,Servant Room             1
Pooja Room,Others,Servant Room                            1
Pooja Room,Others,Servant Room,Study Room                 1
Pooja Room,Store Room,Servant Room,Study Room             1
Servant Room,Pooja Room,Store Room                        1
Others,Store Room                                         1
Servant Room,Pooja Room,Others                            1
Others,Study Room,Pooja Room                              1
Servant Room,Store Room,Pooja Room                        1
Pooja Room,Servant Room,Study Room,Store Room             1
Study Room,Servant Room,Others                            1
Name: count, dtype: int64

In [ ]:
df['additionalRoom'] = df['additionalRoom'].str.lower()

In [ ]:
df.head()

,property_name,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,latitude,longitude,locality,price_per_sqft
0,4BHK 4Baths Flat/Apartment for Sale in DLF Th...,dlf the magnolias,45.00,6400,Super Built-up area 6400(594.58 sq.m.)Built-up...,4,4,3+,"pooja room,study room,servant room,others",Sector 42 Gurgaon,14,North-East,5 to 10 Year Old,"['Ambience Public School', 'Heritage Intl Xper...",Dlf magnolias: An actual gateway of iconic lif...,"['1 Water Purifier', 'Fan', '1 Fridge', '1 Exh...",['Vaastu Compliant'],[],28.454042,77.098740,Gurgaon,70312.0
1,3BHK 3Baths Flat/Apartment for Sale in Godrej...,godrej meridien,2.85,1855,Super Built-up area 1855(172.34 sq.m.) sqft,3,3,3,"pooja room,study room,servant room,others",Sector 106 Gurgaon,8,East,1 to 5 Year Old,"['Dwarka Expressway', 'Euro International Scho...",Looking for a 3 bhk property for sale in gurga...,[],"['Vaastu Compliant', 'Recently Renovated', 'Pi...","['Connectivity: 3.8 out of 5', 'Lifestyle: 3.7...",28.508181,76.986806,Gurgaon,15364.0
2,3BHK 5Baths Flat/Apartment for Sale in Experi...,experion windchants,6.25,3763,Super Built-up area 3763(349.59 sq.m.)Built-up...,3,5,3,servant room,Sector 112 Gurgaon,6,North,5 to 10 Year Old,"['First Step Play School', 'Jai Sai Ram Hospit...",Check out this 3 bhk apartment for sale in exp...,"['Light', 'No AC', 'No Bed', 'No Chimney', 'No...",[],"['Construction: 3.7 out of 5', 'Amenities: 3.9...",28.518719,77.014458,Gurgaon,16609.0
3,3BHK 3Baths Flat/Apartment for Sale in Godrej...,godrej 101,3.50,2125,Super Built-up area 2125(197.42 sq.m.)Carpet a...,3,3,3,servant room,Sector 79 Gurgaon,11,North,By 2027,"['Vatika Town Square-INXT', 'Naurangpur Road',...","Luxury 3 bhk apartment for sale in godrej 101,...",[],[],"['Construction: 3.4 out of 5', 'Amenities: 3.8...",28.359337,76.969227,Gurgaon,16471.0
4,4BHK 4Baths Flat/Apartment for Sale in DLF Ne...,dlf new town heights 1,2.85,2727,Super Built-up area 2727(253.35 sq.m.)Built-up...,4,4,3+,"pooja room,servant room",Sector 90 Gurgaon,4,North-West,5 to 10 Year Old,"['Manish Gallexie 91', 'RHM Public School', 'S...",This beautiful 4 bhk flat in sector 90 gurgaon...,"['5 Wardrobe', 'Fan', '1 Exhaust Fan', '5 Geys...","['Centrally Air Conditioned', 'Vaastu Complian...","['Construction: 3.6 out of 5', 'Amenities: 3.9...",28.403442,76.930775,Gurgaon,10451.0

In [ ]:
df['facing'].value_counts()

facing
East          514
North-East    474
North         275
West          138
North-West     61
South          49
South-East     32
South-West     20
Name: count, dtype: int64

In [ ]:
df['sector'] = df['address'].str.replace('Gurgaon','')

In [ ]:
# features to drop -> property_name, address, description, rating
df.drop(columns=['property_name', 'address', 'description', 'rating','locality'],inplace=True)

In [ ]:
df.head()

,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features,latitude,longitude,price_per_sqft,sector
0,dlf the magnolias,45.00,6400,Super Built-up area 6400(594.58 sq.m.)Built-up...,4,4,3+,"pooja room,study room,servant room,others",14,North-East,5 to 10 Year Old,"['Ambience Public School', 'Heritage Intl Xper...","['1 Water Purifier', 'Fan', '1 Fridge', '1 Exh...",['Vaastu Compliant'],28.454042,77.098740,70312.0,Sector 42
1,godrej meridien,2.85,1855,Super Built-up area 1855(172.34 sq.m.) sqft,3,3,3,"pooja room,study room,servant room,others",8,East,1 to 5 Year Old,"['Dwarka Expressway', 'Euro International Scho...",[],"['Vaastu Compliant', 'Recently Renovated', 'Pi...",28.508181,76.986806,15364.0,Sector 106
2,experion windchants,6.25,3763,Super Built-up area 3763(349.59 sq.m.)Built-up...,3,5,3,servant room,6,North,5 to 10 Year Old,"['First Step Play School', 'Jai Sai Ram Hospit...","['Light', 'No AC', 'No Bed', 'No Chimney', 'No...",[],28.518719,77.014458,16609.0,Sector 112
3,godrej 101,3.50,2125,Super Built-up area 2125(197.42 sq.m.)Carpet a...,3,3,3,servant room,11,North,By 2027,"['Vatika Town Square-INXT', 'Naurangpur Road',...",[],[],28.359337,76.969227,16471.0,Sector 79
4,dlf new town heights 1,2.85,2727,Super Built-up area 2727(253.35 sq.m.)Built-up...,4,4,3+,"pooja room,servant room",4,North-West,5 to 10 Year Old,"['Manish Gallexie 91', 'RHM Public School', 'S...","['5 Wardrobe', 'Fan', '1 Exhaust Fan', '5 Geys...","['Centrally Air Conditioned', 'Vaastu Complian...",28.403442,76.930775,10451.0,Sector 90

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.to_csv('gurgaon_cleaned_properties.csv',index=False)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1563 entries, 0 to 1563
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   society          1563 non-null   object
 1   price            1563 non-null   float64
 2   area             1563 non-null   int64
 3   areaWithType     1563 non-null   object
 4   bedRoom          1563 non-null   int64
 5   bathroom         1563 non-null   int64
 6   balcony          1563 non-null   object
 7   additionalRoom   1563 non-null   object
 8   floorNum         1563 non-null   object
 9   facing           1563 non-null   object
 10  agePossession    1562 non-null   object
 11  nearbyLocations  1563 non-null   object
 12  furnishDetails   1563 non-null   object
 13  features         1563 non-null   object
 14  latitude         1563 non-null   float64
 15  longitude        1563 non-null   float64
 16  price_per_sqft   1563 non-null   float64
 17  sector           1563 non-null   object
dtypes: float64(4), int64(3), object(11)
memory usage: 232.0+ KB